### ISSUE TITLE
User account image upload fails

### ISSUE THREAD

**Issue by flapanther33781** [davidjeddy/yii2-resutoran#6]
The debug message below doesn't tell me anything about why the file upload didn't work.  I'm guessing the file format isn't supported but it doesn't tell me what formats ARE supported either.

```
Intervention\Image\Exception\NotSupportedException
Mar 11, 2017, 5:33:50 PM
[backend][/admin/sign-in/avatar-upload?fileparam=_fileinput_w1]

exception 'Intervention\Image\Exception\NotSupportedException' with message 'GD Library extension not available with this PHP installation.' in /var/www/html/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:16
Stack trace:
#0 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManager.php(108): Intervention\Image\Gd\Driver->__construct()
#1 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\ImageManager->createDriver()
#2 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php(57): Intervention\Image\ImageManager->make('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00...')
#3 /var/www/html/backend/controllers/SignInController.php(47): Intervention\Image\ImageManagerStatic::make('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00...')
#4 [internal function]: backend\controllers\SignInController->backend\controllers\{closure}(Object(trntv\filekit\events\UploadEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Object(Closure), Object(trntv\filekit\events\UploadEvent))
#6 /var/www/html/vendor/trntv/yii2-file-kit/src/actions/UploadAction.php(167): yii\base\Component->trigger('afterSave', Object(trntv\filekit\events\UploadEvent))
#7 /var/www/html/vendor/trntv/yii2-file-kit/src/actions/UploadAction.php(132): trntv\filekit\actions\UploadAction->afterSave('1/meDyYGaxJNgf2...')
#8 [internal function]: trntv\filekit\actions\UploadAction->run()
#9 /var/www/html/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('avatar-upload', Array)
#12 /var/www/html/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('sign-in/avatar-...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /var/www/html/backend/web/index.php(23): yii\base\Application->run()
#15 {main}
```

**Comment by davidjeddy** [comment]
As I am not a fan of GD I have install ImageMagick on the server. Please attempt the action again and provide results.

**Comment by davidjeddy** [comment]
After way too much time spend doing SysOps digging around two things have happened:
1) Know a bit more about nginx + php-fpm config (but not optimization)
2) Profile images work
